Yacine/populating data
remib18/webtoon-like pull request #28
Opened 2022-04-13 20:59 UTC by YacineHB

2022-04-13 21:03 UTC, remib18 requested changes

2022-04-13 21:03 UTC, remib18 commented on site-php/src/pageManager/WebtoonManager.php
> +                //header('Location: /');
Décomenter

2022-04-13 21:03 UTC, remib18 commented on site-php/src/pageManager/WebtoonManager.php
> +            //header('Location: /');
Décompter

2022-04-13 21:47 UTC, remib18 requested changes

2022-04-13 21:47 UTC, remib18 commented on site-php/src/pageManager/WebtoonManager.php
> +    public static function getDescription():stringSSSSSSSS {
string et pas stringSSSSSSSS

2022-04-13 21:47 UTC, remib18 commented on site-php/src/pageManager/WebtoonManager.php
> +    public static function getNbChap():array {
Type de retour devrait être un entier

2022-04-13 21:47 UTC, remib18 commented on site-php/src/pageManager/WebtoonManager.php
> +        return self::getWebtoon()->getNbChap();
La méthode getNbChap n'existe pas sur l'object Webtoon.

2022-04-13 21:47 UTC, remib18 commented on site-php/src/pageManager/WebtoonManager.php
> +    public static function getNbChap():array {
Selon ton code, devrait être renommer et retourner une chaine de caractère contenant le html qui génère les options

2022-04-13 21:47 UTC, remib18 commented on site-php/src/pages/webtoon.php
> +                    <?php foreach(WebtoonManager::getNbChap() as $Chap){?>
Affiche uniquement le contenu de retour de la méthode.

2022-04-13 21:47 UTC, remib18 commented on site-php/src/pageManager/WebtoonManager.php
> +            $res .= '<option value=".(int)$Chapter." selected>Chapitre'.$chapter.'</option>';
$res n'a pas été initialisé au paravant.

2022-04-13 21:47 UTC, remib18 commented on site-php/src/pageManager/WebtoonManager.php
> +            $res .= '<option value=".(int)$Chapter." selected>Chapitre'.$chapter.'</option>';
Toutes les options ne doivent pas être sélectionnées en même temps.
Si le chapitre courant est identique au chapitre, alors il est sélectionner.

2022-04-13 21:47 UTC, remib18 commented on site-php/src/pageManager/WebtoonManager.php
> +            $res .= '<option value=".(int)$Chapter." selected>Chapitre'.$chapter.'</option>';
Pour rappel, tu peux aller sur une page demandant le chapitre 1 du webton 143 avec la requête HTTP suivante : `GET http://localhost/webtoon?id=143&chapter=1`
Si jamais le chapitre n'est pas définit, il faut alors que tu sois rediriger vers le premier chapitre du webtoon.

2022-04-20 15:28 UTC, remib18 approved these changes

2022-04-23 20:09 UTC, remib18 requested changes
La page proposition est cassé...
Tu dois tester avant d'envoyer.

2022-04-24 16:53 UTC, YacineHB reviewed
Home manager à suppr

2022-04-24 16:53 UTC, YacineHB commented on site-php/src/pageManager/HomeManager.php
> +<?php
Y a pas besoin de cet page

2022-05-02 20:30 UTC, YacineHB commented on site-php/src/pageManager/PropositionManager.php
> +        return new TranslationProposition(null,$Proposition,$blockId,$userId,false);
Si qqn passe par là on peux m'expliquer le false. pk il es la? pk pas un true?

2022-05-02 23:25 UTC, onetrickwolfy commented on site-php/src/pageManager/PropositionManager.php
> +        return new TranslationProposition(null,$Proposition,$blockId,$userId,false);
fromDb=false ^^
on s'en sert dans la classe Database!

2022-05-07 18:01 UTC, remib18 requested changes
Retirer les commentaires “inutiles”
Variables et fonctions en camelCase
Commenter les méthodes “longues”
Tester avec des requêtes qui ont
- Des données inéxistantes
- Des données du mauvais type
Synthétiser les isset

2022-05-07 21:36 UTC, onetrickwolfy commented on site-php/src/pageManager/ImportManager.php
> +       if(
Tkt on a fait bcp bcp de tests!

2022-05-07 22:22 UTC, onetrickwolfy commented on site-php/src/utils/Database.php
> +        var_dump($q);
Yep! j'ai du fix car y'avait pas les backquote sur les key des batch.

2022-05-08 14:39 UTC, onetrickwolfy commented on site-php/src/pages/php/TraitementProposition.php
> +    ::setContent(string $content);
C'est broken.
Et si on s'en sert pas, faut delete.

2022-05-08 17:56 UTC, remib18 requested changes

2022-05-08 17:56 UTC, remib18 commented on site-php/assets/styles/app.css
>      }
```suggestion
```

2022-05-08 17:56 UTC, remib18 commented on site-php/src/Settings.php
> +        'webtoonsChapterImage' => '../assets/webtoons-imgs/chapters/'
Mettre des chemins absolus !!!

2022-05-08 17:56 UTC, remib18 commented on site-php/src/pageManager/WebtoonManager.php
> +        return WebtoonController::getById((int)$_GET['id']);
Avec une expression régulière

2022-05-08 17:56 UTC, remib18 commented on site-php/src/pageManager/WebtoonManager.php
> +        $requestedIndex = (int)( $_GET['chapter'] ?? 1 );
```suggestion
        $requestedIndex = (int)($_GET['chapter']) ?? 1;
```

2022-05-08 17:56 UTC, remib18 commented on site-php/src/pages/php/TraitementProposition.php
> +    ::setContent(string $content);
On ne peut pas merge avec ça

2022-05-08 19:29 UTC, onetrickwolfy commented on site-php/src/Settings.php
> +        'webtoonsChapterImage' => '../assets/webtoons-imgs/chapters/'
honnêtement je trouve pas cela une bonne idee.
Faudrait que les profs mettent les chemins avant de tester et ca serait vachement casse couille

2022-05-08 19:30 UTC, onetrickwolfy commented on site-php/src/pages/php/TraitementProposition.php
> +    ::setContent(string $content);
terst

2022-05-09 11:33 UTC, remib18 submitted a review, later dismissed

2022-05-09 12:12 UTC, onetrickwolfy submitted a review, later dismissed

2022-05-09 13:03 UTC, merged