Implémentation d'un système d'utilisateur simple.
remib18/webtoon-like pull request #47
Opened 2022-04-29 14:46 UTC by onetrickwolfy

2022-04-30 01:39 UTC, remib18 requested changes

2022-04-30 01:39 UTC, remib18 commented on site-php/src/controller/UserController.php
> +        return Database::getAll('user', User::class, $col, $where);
Majuscule à user

2022-04-30 01:39 UTC, remib18 commented on site-php/src/controller/UserController.php
> +        return Database::getFirst('User', user::class, '*', ['userID' => "userID = $id"]);
`user` => `User`

2022-04-30 01:39 UTC, remib18 commented on site-php/src/controller/UserController.php
> +        return Database::getFirst('User', user::class, '*', ['email' => "email = '$email'"]);
`user` => `User`

2022-04-30 01:39 UTC, remib18 commented on site-php/src/controller/UserController.php
> +        return Database::getFirst('User', user::class, '*', ['username' => "username = '$username'"]);
`user` => `User`

2022-04-30 01:39 UTC, remib18 commented on site-php/src/core/Authentication.php
> +    public static function innitSession(): void {
probablement plus pratique de le mettre en privé puis de l'appeler dans chaque méthode.

2022-04-30 01:39 UTC, remib18 commented on site-php/src/core/Authentication.php
> +    public static function register(String $username, String $email, String $password, string $password_confirmation): bool|array
`String` => `string`

2022-04-30 01:39 UTC, remib18 commented on site-php/src/helpers/UrlHelper.php
> +    public static function buildUrl(string $uri, array $parameter): string {
Déplacer dans UriUtils

2022-04-30 01:39 UTC, remib18 commented on site-php/src/index.php
> +Authentication::innitSession(); // Todo: deplace au bon endroit.
Modifier l'emplacement / supprimer

2022-04-30 01:39 UTC, remib18 commented on site-php/src/pages/php/login.php
> +    <form action="/@login" method="post" required>
le form ne peut pas être required

2022-04-30 01:39 UTC, remib18 commented on site-php/src/pages/php/login.php
> +    <form action="/@login" method="post" required>
Ajouter les identifiants et les labels pour chaque inputs

2022-04-30 01:39 UTC, remib18 commented on site-php/src/pages/php/register.php
> +    <form action="/@register" method="post">
Ajouter les identifiants et les labels

2022-04-30 14:22 UTC, onetrickwolfy commented on site-php/src/helpers/UrlHelper.php
> +    public static function buildUrl(string $uri, array $parameter): string {
finalement j'en ai pas eu besoin / y a deja un methode dans uriUtils

2022-04-30 16:39 UTC, remib18 requested changes

2022-04-30 16:39 UTC, remib18 commented on site-php/src/core/Authentication.php
> +    public static function register(String $username, String $email, String $password, string $password_confirmation): bool|array
dans les types

2022-05-01 10:01 UTC, remib18 approved these changes

2022-05-01 10:01 UTC, merged