Ajout fonctionnalité remember-me
remib18/webtoon-like pull request #48
Opened 2022-05-01 10:18 UTC by onetrickwolfy

2022-05-01 10:39 UTC, remib18 requested changes

2022-05-01 10:39 UTC, remib18 commented on site-php/src/core/Authentication.php
> +            if($tokenEntity === null) return;
Remplacer l'égalité par is_null

2022-05-01 10:39 UTC, remib18 commented on site-php/src/core/Authentication.php
> +        if(isset($_COOKIE['rememberMe']) && !empty($_COOKIE['rememberMe']) && $_SESSION['accessLevel'] === AccessLevel::everyone) {
Inverser la condition pour supprimer le else : la condition d'exécution devient une condition d'échec.

2022-05-01 10:39 UTC, remib18 commented on site-php/src/core/Authentication.php
> +            $token = mysqli_real_escape_string(Database::getDB(), $_COOKIE['rememberMe']);
Est tu a 100% sur que cette donnée est unique, même différentes fois pour un même utilisateur ?

2022-05-01 10:39 UTC, remib18 commented on site-php/src/entities/LoginToken.php
> +        $this->id = $token;
Pourquoi sauvegarder le token dans un champ id alors qu'il est déjà sauvegardé dans un champ token ???

2022-05-01 10:39 UTC, remib18 commented on site-php/src/entities/LoginToken.php
> +    public function setId(int $id): void {
Le set Id est impossible...
Il s'agit d'une valeur d'indexation. Elle ne peut pas changer dans le temps.

2022-05-01 10:39 UTC, remib18 commented on site-php/src/entities/LoginToken.php
> +    public function setToken(string $token): void
Le set Token est impossible...
Il s'agit d'une valeur d'indexation. Elle ne peut pas changer dans le temps.

2022-05-01 10:39 UTC, remib18 commented on site-php/src/handlers/login.php
>      || empty($_POST['email'])
Test du mdp vide ?

2022-05-01 10:39 UTC, remib18 commented on site-php/src/pages/php/login.php
> +            <input type="checkbox" name="rememberMe">
Manque l'identifiant associé au label...

2022-05-01 10:39 UTC, remib18 commented on site-php/src/utils/Database.php
> +        $q = "DELETE FROM `$table` WHERE " . $where;
Ne change rien

2022-05-01 10:39 UTC, remib18 commented on site-php/src/utils/Database.php
> +        var_dump($q);
Retirer le var dump

2022-05-01 10:39 UTC, remib18 commented on site-php/src/utils/Database.php
>          }
Remet juste l'espace après le =

2022-05-01 10:39 UTC, remib18 commented on site-php/src/controller/LoginTokenController.php
> +    public static function remove(LoginToken $entity): bool
La donnée doit être liée (`&$entity`)

2022-05-01 10:53 UTC, onetrickwolfy commented on site-php/src/core/Authentication.php
> +            $token = mysqli_real_escape_string(Database::getDB(), $_COOKIE['rememberMe']);
1 chance sur 4294967296 qu'elle ne soit pas unique.
Je peux monter sur du  1 / 1.84467440737e+19 si tu veux.

2022-05-01 10:55 UTC, onetrickwolfy commented on site-php/src/core/Authentication.php
> +            $token = mysqli_real_escape_string(Database::getDB(), $_COOKIE['rememberMe']);
1 chance sur 1.84467440737e+19 qu'elle ne soit pas unique.

2022-05-01 11:03 UTC, onetrickwolfy commented on site-php/src/handlers/login.php
>      || empty($_POST['email'])
Je ne comprends pas?

|| empty($_POST['password']))  est deja la.

2022-05-01 17:16 UTC, remib18 requested changes
Tu n'as pas pris en compte mes suggestions...

2022-05-01 17:16 UTC, remib18 commented on site-php/src/utils/Database.php
> +        $q = "DELETE FROM `$table` WHERE " . $where;
Pourquoi cette modification qui ne change rien ?

2022-05-01 17:16 UTC, remib18 commented on site-php/src/utils/Database.php
> +        var_dump($q);
!!!

2022-05-01 17:16 UTC, remib18 commented on site-php/src/utils/Database.php
>          }
!!!

2022-05-01 17:16 UTC, remib18 commented on site-php/src/pages/php/login.php
> +            <input type="checkbox" name="rememberMe">
à l'intérieur de l'input

2022-05-01 17:16 UTC, remib18 commented on site-php/src/entities/LoginToken.php
> +    public function setId(int $id): void {
A retirer

2022-05-01 17:17 UTC, remib18 commented on site-php/src/handlers/login.php
>      || empty($_POST['email'])
Je ne le vois pas ?

2022-05-02 10:27 UTC, remib18 approved these changes

2022-05-02 10:28 UTC, merged