Suppression des comptes et menu actions.
remib18/webtoon-like pull request #56
Opened 2022-05-02 19:36 UTC by onetrickwolfy

J'ai fait un page action qui contiendra diverses actions telles que: 
- Je souhaite supprimer mon compte
- Je souhaite devenir editeur
- Je souhaite contacter le support...

Un précurseur à un page de settings en quelque sort. 

**De plus**, il est désormais possible de *supprimer* son compte.
Je le fais à la discord, on remplace les nom et email par deletedAccount.

C'est important de garder les userId pour les contributions.

2022-05-04 21:40 UTC, remib18 requested changes

2022-05-04 21:40 UTC, remib18 commented on site-php/src/entities/User.php
> +    public function getDeleted(): bool {
```suggestion
    public function isDeleted(): bool {
```

2022-05-04 21:40 UTC, remib18 commented on site-php/src/handlers/deleteAccount.php
> +if($res === true) {
```suggestion
if($res) {
```

2022-05-04 21:40 UTC, remib18 commented on site-php/src/pages/php/register.php
> +                   autocomplete="off",
```suggestion
                   autocomplete="off"
```

2022-05-04 21:40 UTC, remib18 commented on site-php/src/pages/php/register.php
> +                   autocomplete="on",
```suggestion
                   autocomplete="on"
```

2022-05-04 21:40 UTC, remib18 commented on site-php/src/pages/php/register.php
> +                   autocomplete="on",
```suggestion
                   autocomplete="on"
```

2022-05-04 21:40 UTC, remib18 commented on site-php/src/pages/php/register.php
> +                   autocomplete="off",
```suggestion
                   autocomplete="off"
```

2022-05-05 13:44 UTC, closed without merging

2022-05-05 13:45 UTC, remib18 commented
Fermer car une branche plus à jour basée sur celle-ci va être push.

2022-05-05 14:27 UTC, onetrickwolfy commented
> Fermer car une branche plus à jour basée sur celle-ci va être push.
> 
> Voir [la pull request correspondante](https://github.com/remib18/webtoon-like/pull/57).

Celle-ci plutôt! https://github.com/remib18/webtoon-like/pull/59